name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: helloworld-a
    steps:
      - uses: actions/checkout@v4


      - name: Loop over each image line and run jq
        run: |
          pwd
          ls
          while IFS= read -r line; do
            echo "Processing: $line"
            
            # Extract name and tag
            name="${line%%:*}"
            tag="${line##*:}"

            echo "Name: $name"
            echo "Tag: $tag"
            yq eval ".service.image |= sub(\":[^:]+$\", \":${tag}\")" -i ${name}.yaml
          done < /dev/versions.yaml
          cat dev/helloworld-a.yaml
          cat dev/helloworld-b.yaml
          

